setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
# ==============================================================================
# ADVERTISEMENT DEDUPLICATION & FILTERING PIPELINE
# ==============================================================================
rm(list = ls())

# ==============================================================================
# 1. LIBRARIES
# ==============================================================================
library(dplyr)
library(stringr)
library(readxl)

# ==============================================================================
# 2. PATHS & CONFIGURATION
# ==============================================================================

# Note: Update INPUT_RDS to "Mailout_Ads.rds" when processing your other dataset,
# or to a combined dataset RDS if you merge them beforehand.
paths <- list(
  INPUT_RDS   = "C:/Users/unity/Documents/Dissertation/Newspaper_Ads.rds",
  CODING_FILE = "C:/Users/unity/Documents/Dissertation/Advertisement Coding.xlsx",
  OUTPUT_RDS  = "C:/Users/unity/Documents/Dissertation/Filtered_Ads.rds"
)

# Parameters for duplicate removal
JACCARD_THRESHOLD <- 0.85
LENGTH_TOLERANCE  <- 0.20 # +/- 20%

# ==============================================================================
# 3. HELPER FUNCTIONS
# ==============================================================================

#-------------------------------------------------------
# Remove Jaccard Duplicates with Length Tolerance
#-------------------------------------------------------
remove_jaccard_duplicates <- function(df, threshold, length_tol) {
  
  cat("Starting Jaccard deduplication...\n")
  cat("Total starting rows:", nrow(df), "\n")
  
  # Ensure Total_Tokens is numeric
  df$Total_Tokens <- as.numeric(df$Total_Tokens)
  
  duplicates_to_remove <- integer(0)
  n_rows <- nrow(df)
  
  # Pre-compute word sets to optimize the nested loop
  # Uses CleanedText as generated by the OCR pipeline
  word_sets <- lapply(df$CleanedText, function(text) {
    unique(unlist(str_split(text, "\\s+")))
  })
  
  for (i in seq_len(n_rows - 1)) {
    
    # Skip if already marked for removal
    if (i %in% duplicates_to_remove) next
    
    len_i <- df$Total_Tokens[i]
    set_i <- word_sets[[i]]
    
    for (j in (i + 1):n_rows) {
      
      # Skip if already marked for removal
      if (j %in% duplicates_to_remove) next
      
      len_j <- df$Total_Tokens[j]
      
      # Step 1: Check Length Tolerance (+/- 20%)
      lower_bound <- len_i * (1 - length_tol)
      upper_bound <- len_i * (1 + length_tol)
      
      if (len_j >= lower_bound && len_j <= upper_bound) {
        
        # Step 2: Calculate Jaccard Similarity
        set_j <- word_sets[[j]]
        
        intersect_len <- length(intersect(set_i, set_j))
        union_len <- length(set_i) + length(set_j) - intersect_len
        
        jaccard_sim <- ifelse(union_len == 0, 0, intersect_len / union_len)
        
        # Step 3: Flag for removal if threshold is met
        if (jaccard_sim >= threshold) {
          duplicates_to_remove <- c(duplicates_to_remove, j)
        }
      }
    }
  }
  
  # Remove flagged indices and report
  if (length(duplicates_to_remove) > 0) {
    cat(sprintf("Removed %d duplicate(s) (Similarity >= %s, Length Tol = +/- %s%%)\n", 
                length(duplicates_to_remove), threshold, length_tol * 100))
    return(df[-duplicates_to_remove, ])
  } else {
    cat("No duplicates found meeting the criteria.\n")
    return(df)
  }
}

# ==============================================================================
# 4. EXECUTION BLOCK
# ==============================================================================

# Load OCR Data
cat("Loading RDS dataset...\n")
ads_df <- readRDS(paths$INPUT_RDS)

# Load Coding Excel Sheet
cat("Loading Advertisement Coding spreadsheet...\n")
coding_df <- read_excel(paths$CODING_FILE)

#-------------------------------------------------------
# Filter Out Animal Advertisements
#-------------------------------------------------------
cat("\nFiltering out 'Is_Animal == 1' advertisements...\n")

# Identify Ad_Base_IDs flagged as animals
animal_ads <- coding_df |>
  filter(Is_Animal == 1) |>
  pull(Ad_Base_ID)

# Remove these IDs from the main dataset
ads_df_filtered <- ads_df |>
  filter(!Ad_Base_ID %in% animal_ads)

cat("Removed", nrow(ads_df) - nrow(ads_df_filtered), "animal-related advertisements.\n")

#-------------------------------------------------------
# Remove Jaccard Duplicates
#-------------------------------------------------------
cat("\nRunning deduplication process...\n")

final_clean_df <- remove_jaccard_duplicates(
  df = ads_df_filtered, 
  threshold = JACCARD_THRESHOLD, 
  length_tol = LENGTH_TOLERANCE
)

#-------------------------------------------------------
# Save Output
#-------------------------------------------------------
cat("\nSaving filtered dataset to:", paths$OUTPUT_RDS, "\n")
saveRDS(final_clean_df, paths$OUTPUT_RDS)

cat("Pipeline complete. Final advertisement count:", nrow(final_clean_df), "\n")

newspaper_ads <- readRDS("Filtered_Ads.rds")
print


###################################################################################
#-------------------------------------------------------
# Identify Potential Duplicates for Manual Review
#-------------------------------------------------------
find_duplicate_candidates <- function(df, threshold = 0.70) {
  cat("Scanning for potential duplicates (Similarity >= ", threshold, ")... \n")
  
  df$Total_Tokens <- as.numeric(df$Total_Tokens)
  n_rows <- nrow(df)
  
  # Pre-compute word sets
  word_sets <- lapply(df$CleanedText, function(text) {
    unique(unlist(str_split(text, "\\s+")))
  })
  
  # Initialize result list
  candidate_list <- list()
  counter <- 1
  
  for (i in seq_len(n_rows - 1)) {
    set_i <- word_sets[[i]]
    id_i <- df$Ad_Base_ID[i]
    
    for (j in (i + 1):n_rows) {
      set_j <- word_sets[[j]]
      id_j <- df$Ad_Base_ID[j]
      
      # Calculate Jaccard
      intersect_len <- length(intersect(set_i, set_j))
      union_len <- length(set_i) + length(set_j) - intersect_len
      jaccard_sim <- ifelse(union_len == 0, 0, intersect_len / union_len)
      
      # Flag if meets threshold
      if (jaccard_sim >= threshold) {
        candidate_list[[counter]] <- data.frame(
          Ad_1 = id_i,
          Ad_2 = id_j,
          Similarity = round(jaccard_sim, 3)
        )
        counter <- counter + 1
      }
    }
  }
  
  if (length(candidate_list) > 0) {
    results <- do.call(rbind, candidate_list)
    return(results)
  } else {
    cat("No pairs found above", threshold, "\n")
    return(NULL)
  }
}

duplicate_audit <- find_duplicate_candidates(newspaper_ads, threshold = 0.70)

# 2. Print to console
if (!is.null(duplicate_audit)) {
  cat("\n--- ADVERTISEMENTS WITH JACCARD SIMILARITY >= 0.75 ---\n")
  print(duplicate_audit)
} else {
  cat("\nNo duplicates found above the 0.75 threshold.\n")
}


######################################################################################

library(dplyr)
library(stringr)

# 1. Load your coding results
# Ensure 'newspaper_ads' is already in your environment before running this
coding_results <- read.csv("Manual_Review_Coding_Sheet.csv")

# 2. Normalize the CSV (Coding) IDs (taking the last 3 characters)
coding_results_norm <- coding_results %>%
  filter(Manual_Decision == "YES") %>%
  mutate(
    Ad_1_Norm = str_sub(as.character(Ad_1), -3, -1),
    Ad_2_Norm = str_sub(as.character(Ad_2), -3, -1)
  )

# 3. Normalize the RDS (Main) IDs (taking the first 3 characters)
newspaper_ads_norm <- newspaper_ads %>%
  mutate(
    Row_Index = row_number(),
    Ad_Base_ID_Norm = str_sub(as.character(Ad_Base_ID), 1, 3)
  )

# 4. Join using the Normalized columns
comparison_table <- coding_results_norm %>%
  left_join(newspaper_ads_norm %>% select(Ad_Base_ID, Ad_Base_ID_Norm, NoiseRatio, Row_Index), 
            by = c("Ad_1_Norm" = "Ad_Base_ID_Norm")) %>%
  rename(Noise_1 = NoiseRatio, Row_1 = Row_Index) %>%
  left_join(newspaper_ads_norm %>% select(Ad_Base_ID, Ad_Base_ID_Norm, NoiseRatio, Row_Index), 
            by = c("Ad_2_Norm" = "Ad_Base_ID_Norm")) %>%
  rename(Noise_2 = NoiseRatio, Row_2 = Row_Index)

# 5. Identify and remove duplicates
ids_to_remove <- apply(comparison_table, 1, function(row) {
  n1 <- as.numeric(row['Noise_1'])
  n2 <- as.numeric(row['Noise_2'])
  r1 <- as.numeric(row['Row_1'])
  r2 <- as.numeric(row['Row_2'])
  
  if (is.na(n1) || is.na(n2)) return(NA)
  
  if (n1 > n2) return(row['Ad_1']) 
  else if (n2 > n1) return(row['Ad_2']) 
  else if (r1 < r2) return(row['Ad_1']) 
  else return(row['Ad_2'])
})

# Filter the dataset and save it
final_clean_newspaper_ads <- newspaper_ads %>%
  filter(!Ad_Base_ID %in% ids_to_remove[!is.na(ids_to_remove)])

# Save the file so you don't lose it again
saveRDS(final_clean_newspaper_ads, "Final_Cleaned_Newspaper_Ads.rds")

cat("Successfully cleaned and saved to Final_Cleaned_Newspaper_Ads.rds\n")


#####################################################################################

# 1. Define your manual exclusion list here
# Add any extra IDs you discovered in the previous steps
ids_to_manually_exclude <- c(
  "102"
)

# 2. Final clean
final_clean_newspaper_ads <- final_clean_newspaper_ads %>%
  filter(!Ad_Base_ID %in% ids_to_manually_exclude)

# 3. Overwrite the RDS with your new, verified clean version
saveRDS(final_clean_newspaper_ads, "Final_Cleaned_Newspaper_Ads.rds")

cat("Final cleanup complete. Total ads remaining:", nrow(final_clean_newspaper_ads), "\n")

#########################################################################################
library(dplyr)
library(stringdist)

# 1. Calculate Error Rate
ads_for_review <- final_clean_newspaper_ads %>%
  mutate(Error_Rate = 1 - (Dictionary_Words / Total_Tokens))

# 2. Extract text and names
text_vector <- ads_for_review$CleanedText
names(text_vector) <- ads_for_review$Ad_Base_ID

# 3. Calculate similarity matrix
dist_mat <- stringdistmatrix(text_vector, text_vector, method = "jw")
dimnames(dist_mat) <- list(names(text_vector), names(text_vector))

# 4. Convert and apply BALANCED FILTERS
review_sheet <- as.data.frame(as.table(dist_mat)) %>%
  rename(Ad_1 = Var1, Ad_2 = Var2, Distance = Freq) %>%
  filter(as.character(Ad_1) < as.character(Ad_2)) %>%
  
  # Bring in token counts and error rates for comparison
  left_join(ads_for_review %>% select(Ad_Base_ID, Tokens_1 = Total_Tokens, Error_1 = Error_Rate, Text_1 = CleanedText), by = c("Ad_1" = "Ad_Base_ID")) %>%
  left_join(ads_for_review %>% select(Ad_Base_ID, Tokens_2 = Total_Tokens, Error_2 = Error_Rate, Text_2 = CleanedText), by = c("Ad_2" = "Ad_Base_ID")) %>%
  
  # --- THE BALANCED FIX ---
  # Filter 1: Allow up to 30% difference in word count (catches ads where OCR dropped a paragraph)
  filter(abs(Tokens_1 - Tokens_2) / pmax(Tokens_1, Tokens_2) < 0.30) %>%
  # Filter 2: Relaxed text distance to allow for OCR gibberish variations
  filter(Distance < 0.15) %>% 
  arrange(Distance) %>%
  
  # Format for Excel
  mutate(Is_Duplicate = "") %>%
  select(Is_Duplicate, Distance, Ad_1, Ad_2, Tokens_1, Tokens_2, Error_1, Error_2, Text_1, Text_2)

# 5. Export to CSV
write.csv(review_sheet, "Round2_Duplicate_Review.csv", row.names = FALSE)
cat("Exported", nrow(review_sheet), "highly likely duplicate pairs to 'Round2_Duplicate_Review.csv'\n")


###########################################################################################
library(dplyr)

# 1. Load your manually reviewed Round 2 sheet
reviewed_sheet <- read.csv("Round2_Duplicate_Review.csv", stringsAsFactors = FALSE) %>%
  # Use the correct column name for Round 2
  filter(toupper(trimws(Is_Duplicate)) == "YES")

if(nrow(reviewed_sheet) > 0) {
  # 2. Determine which ID to drop based on the Error Rate already in the CSV
  ids_to_drop <- apply(reviewed_sheet, 1, function(row) {
    err1 <- as.numeric(row["Error_1"])
    err2 <- as.numeric(row["Error_2"])
    
    # Drop the ad with the HIGHER error rate (more OCR noise)
    if (!is.na(err1) && !is.na(err2)) {
      if (err1 > err2) return(row["Ad_1"])
      else return(row["Ad_2"])
    } else {
      return(row["Ad_2"]) # Fallback if error rates are missing
    }
  })
  
  # Clean up the drop list to ensure no blank/duplicate IDs
  ids_to_drop <- unique(ids_to_drop[!is.na(ids_to_drop)])
  
  # 3. Perform the removal ON THE ALREADY CLEANED DATASET
  final_clean_newspaper_ads <- final_clean_newspaper_ads %>%
    filter(!Ad_Base_ID %in% ids_to_drop)
  
  # 4. Save the finalized dataset
  saveRDS(final_clean_newspaper_ads, "Final_Cleaned_Newspaper_Ads.rds")
  
  cat("Successfully removed", length(ids_to_drop), "Round 2 duplicates.\n")
  cat("Total ads remaining:", nrow(final_clean_newspaper_ads), "\n")
  
} else {
  cat("No duplicates marked 'YES' found in the review sheet.\n")
}

##################################################################################
library(dplyr)
library(stringdist)

# 1. Calculate Error Rate on your current clean dataset
ads_for_review <- final_clean_newspaper_ads %>%
  mutate(Error_Rate = 1 - (Dictionary_Words / Total_Tokens))

# 2. Extract text and names
text_vector <- ads_for_review$CleanedText
names(text_vector) <- ads_for_review$Ad_Base_ID

# 3. Calculate similarity matrix
dist_mat <- stringdistmatrix(text_vector, text_vector, method = "jw")
dimnames(dist_mat) <- list(names(text_vector), names(text_vector))

# 4. Apply LOOSER FILTERS to catch more hidden duplicates
review_sheet <- as.data.frame(as.table(dist_mat)) %>%
  rename(Ad_1 = Var1, Ad_2 = Var2, Distance = Freq) %>%
  filter(as.character(Ad_1) < as.character(Ad_2)) %>%
  
  # Bring in token counts and error rates for comparison
  left_join(ads_for_review %>% select(Ad_Base_ID, Tokens_1 = Total_Tokens, Error_1 = Error_Rate, Text_1 = CleanedText), by = c("Ad_1" = "Ad_Base_ID")) %>%
  left_join(ads_for_review %>% select(Ad_Base_ID, Tokens_2 = Total_Tokens, Error_2 = Error_Rate, Text_2 = CleanedText), by = c("Ad_2" = "Ad_Base_ID")) %>%
  
  # --- THE LOOSER THRESHOLDS ---
  # Filter 1: Allow up to 40% difference in word count
  filter(abs(Tokens_1 - Tokens_2) / pmax(Tokens_1, Tokens_2) < 0.40) %>%
  # Filter 2: Looser text distance (0.20) to catch heavy OCR noise
  filter(Distance < 0.18) %>% 
  arrange(Distance) %>%
  
  # Format for Excel
  mutate(Is_Duplicate = "") %>%
  select(Is_Duplicate, Distance, Ad_1, Ad_2, Tokens_1, Tokens_2, Error_1, Error_2, Text_1, Text_2)

# 5. Export to CSV
write.csv(review_sheet, "Round3_Duplicate_Review.csv", row.names = FALSE)
cat("Exported", nrow(review_sheet), "potential duplicate pairs to 'Round3_Duplicate_Review.csv'\n")









####################################################################################
library(dplyr)

# 1. Load your manually reviewed Round 3 sheet
reviewed_sheet <- read.csv("Round3_Duplicate_Review.csv", stringsAsFactors = FALSE) %>%
  filter(toupper(trimws(Is_Duplicate)) == "YES")

if(nrow(reviewed_sheet) > 0) {
  # 2. Determine which ID to drop
  ids_to_drop <- apply(reviewed_sheet, 1, function(row) {
    err1 <- as.numeric(row["Error_1"])
    err2 <- as.numeric(row["Error_2"])
    
    if (!is.na(err1) && !is.na(err2)) {
      if (err1 > err2) return(row["Ad_1"])
      else return(row["Ad_2"])
    } else {
      return(row["Ad_2"])
    }
  })
  
  ids_to_drop <- unique(ids_to_drop[!is.na(ids_to_drop)])
  
  # 3. Perform the removal
  final_clean_newspaper_ads <- final_clean_newspaper_ads %>%
    filter(!Ad_Base_ID %in% ids_to_drop)
  
  # 4. Save the finalized dataset
  saveRDS(final_clean_newspaper_ads, "Final_Cleaned_Newspaper_Ads.rds")
  
  cat("Successfully removed", length(ids_to_drop), "Round 3 duplicates.\n")
  cat("Total ads remaining:", nrow(final_clean_newspaper_ads), "\n")
  
} else {
  cat("No duplicates marked 'YES' found in the review sheet.\n")
}


=#################################################################################

library(dplyr)
library(igraph)

# ==============================================================================
# FINAL IMAGE-BASED DUPLICATE & ANIMAL EXCLUSION
# ==============================================================================

cat("\nStarting final cleanup based on coding sheet...\n")

# 1. Load the finalized dataset from your previous steps
# (Assuming it's already in your environment, but here for completeness)
# final_clean_newspaper_ads <- readRDS("Final_Cleaned_Newspaper_Ads.rds")

# 2. Define the manual animal exclusions explicitly
animal_exclusions <- c("163", "253")

# 3. Hardcode the duplicate pairs derived directly from "image_946382.png"
image_dup_pairs <- data.frame(
  Ad_1 = c("042", "039", "025", "004", "001", "081", "097", "081", 
           "083", "039", "048", "103", "103", "120", "097", "100", 
           "152", "092", "162", "103", "120", "167", "120", "103", 
           "246", "076", "264", "286", "307", "331", "307", "049"),
  Ad_2 = c("045", "048", "038", "022", "010b", "083", "100", "115", 
           "115", "119", "119", "120", "143", "143", "151", "151", 
           "155", "158", "166", "167", "167", "174", "174", "174", 
           "250", "273", "285", "297", "343", "343", "331", "308"),
  stringsAsFactors = FALSE
)

# 4. Use igraph to group overlapping pairs into single clusters
g <- graph_from_data_frame(image_dup_pairs, directed = FALSE)
clusters <- components(g)

cluster_map <- data.frame(
  Ad_Base_ID = names(clusters$membership),
  Cluster = clusters$membership,
  stringsAsFactors = FALSE
)

# 5. Join cluster mapping to the dataset to isolate the duplicates
ads_in_clusters <- final_clean_newspaper_ads %>%
  inner_join(cluster_map, by = "Ad_Base_ID")

# 6. Identify the ads with the highest noise to remove using NoiseRatio
ids_to_drop_from_clusters <- ads_in_clusters %>%
  group_by(Cluster) %>%
  # Sort by noise ascending (lowest noise stays at the top)
  arrange(NoiseRatio) %>%
  # Slice removes the first row (the cleanest ad to keep) and keeps the noisier ones to drop
  slice(-1) %>%
  pull(Ad_Base_ID)

# 7. Combine all IDs slated for removal
all_drops <- unique(c(animal_exclusions, ids_to_drop_from_clusters))

# 8. Filter the main dataset
final_clean_newspaper_ads <- final_clean_newspaper_ads %>%
  filter(!Ad_Base_ID %in% all_drops)

# 9. Overwrite the RDS with the absolutely finalized data
saveRDS(final_clean_newspaper_ads, "Final_Cleaned_Newspaper_Ads.rds")

cat("Successfully removed", length(ids_to_drop_from_clusters), "noisy duplicates and", length(animal_exclusions), "animal ads.\n")
cat("Final total ads remaining:", nrow(final_clean_newspaper_ads), "\n")